<?php

class afPDF extends FPDF {
	
	public
	$widget,
	$af_version, 
	$widths,
	$borders,
	$fills,
	$aligns;
	
	public function Header()
	{
	    $this->SetFont('Arial','B',10);
	    $this->Cell(0,10,ucwords($this->widget["title"])." Widget","B",1,"L");
	    $this->Ln(5);
	}
	
	function Footer()
	{
	    $this->SetY(-15);
	    $this->SetFont('Arial','I',8);
	    $this->Cell(0,10,'Generated by AppFlower '.$this->af_version.' - Page '.$this->PageNo().' / {nb}',"T",0,'C');	
		
	}


	function SetWidths($w)
	{
	    //Set the array of column widths
	    $this->widths=$w;
	}
	
	function SetAligns($a)
	{
	    //Set the array of column alignments
	    $this->aligns=$a;
	}
	
	function SetBorders($b)
	{
	    //Set the array of borders
	    $this->borders=$b;
	}
	
	function SetFills($f)
	{
	    //Set the array of borders
	    $this->fills=$f;
	}
	
	public function getMaxCellHeight($data) {
		
		foreach($data as $str) {
			if(strstr($str,"\n")) {
				$tmp[] = substr_count($str,"\n");
			} else {
				$tmp[] = 0;
			}
		}
		
		return max($tmp)+1;
		
	}
	
	public function Row($data,$form = false,$extra_borders = array(),$border_width = 0.2,$cell_height = 5)
	{
		
		$this->setLineWidth($border_width);
		
	    //Calculate the height of the row
	    $nb=0;
	    for($i=0;$i<count($data);$i++)
	        $nb=max($nb,$this->NbLines($this->widths[$i],$data[$i]));
	    $h=$cell_height*$nb;
	    //Issue a page break first if needed
	    $this->CheckPageBreak($h);
	    //Draw the cells of the row
	    for($i=0;$i<count($data);$i++)
	    {
	        $w=$this->widths[$i];
	        $a=isset($this->aligns[$i]) ? $this->aligns[$i] : 'L';
	        $B=isset($this->borders[$i]) ? $this->borders[$i] : 0;
	        $BW=isset($this->border_widths[$i]) ? $this->border_widths[$i] : 0.2;
	        
	        if(isset($extra_borders[$i])) {
	        	$B = $extra_borders[$i];
	        } 
	        
	        $F=isset($this->fills[$i]) ? $this->fills[$i] : 0;
	        //Save the current position
	        $x=$this->GetX();
	        $y=$this->GetY();
	        
	        // Set fill color (if any)
	        if($F) {
	        	$this->setFillColor($F[0],$F[$i][1],$F[$i][2]);
	        } else {
	        	$this->setFillColor(255,255,255);
	        }
	        
	        if(!$form) {
	       		 $B = 0;
	       		 if($F) {
	       		 	$F = "FD";
	       		 } else {
	       		 	$F = "D";
	       		 }
	       		 $this->Rect($x,$y,$w,$h,$F); 	
	        }
	       
	        //Print the text
	        $this->MultiCell($w,$cell_height,$data[$i],$B,$a,$form);
	        //Put the position to the right of the cell
	        $this->SetXY($x+$w,$y);
	    }
	    //Go to the next line
	    $this->Ln($h);
	}
	
	function CheckPageBreak($h)
	{
	    //If the height h would cause an overflow, add a new page immediately
	    if($this->GetY()+$h>$this->PageBreakTrigger)
	        $this->AddPage($this->CurOrientation);
	}
	
	function NbLines($w,$txt)
	{
	    //Computes the number of lines a MultiCell of width w will take
	    $cw=&$this->CurrentFont['cw'];
	    if($w==0)
	        $w=$this->w-$this->rMargin-$this->x;
	    $wmax=($w-2*$this->cMargin)*1000/$this->FontSize;
	    $s=str_replace("\r",'',$txt);
	    $nb=strlen($s);
	    if($nb>0 and $s[$nb-1]=="\n")
	        $nb--;
	    $sep=-1;
	    $i=0;
	    $j=0;
	    $l=0;
	    $nl=1;
	    while($i<$nb)
	    {
	        $c=$s[$i];
	        if($c=="\n")
	        {
	            $i++;
	            $sep=-1;
	            $j=$i;
	            $l=0;
	            $nl++;
	            continue;
	        }
	        if($c==' ')
	            $sep=$i;
	        $l+=$cw[$c];
	        if($l>$wmax)
	        {
	            if($sep==-1)
	            {
	                if($i==$j)
	                    $i++;
	            }
	            else
	                $i=$sep+1;
	            $sep=-1;
	            $j=$i;
	            $l=0;
	            $nl++;
	        }
	        else
	            $i++;
	    }
	    return $nl;
	}
}

?>